export type DoctorQueueItem = {
  intake_session_id: string;
  token: string;
  patient_id: string;
  patient_name: string;
  patient_age: number | null;
  patient_gender: string | null;
  chief_complaint: string;
  language_code: string;
  workflow_type: string;
  status: 'WAITING' | 'HISTORY_READY' | 'PRIORITY_REVIEW' | 'IN_REVIEW' | 'CONFIRMED';
  status_tone: 'teal' | 'amber' | 'red';
  priority: 'Priority' | 'Routine';
  has_red_flags: boolean;
  submitted_at: string;
  wait_time_minutes: number;
  abha_id?: string | null;
  abha_status?: string | null;
};

export type PatientDetail = {
  intake_session_id: string;
  token: string;
  patient_id: string;
  patient_name: string;
  patient_age: number | null;
  patient_gender: string | null;
  phone?: string | null;
  date_of_birth?: string | null;
  abha_id?: string | null;
  abha_address?: string | null;
  abha_status?: string | null;
  consent_recorded?: boolean;
  hospital_name: string;
  doctor_name: string;
  workflow_type: string;
  language_code: string;
  status: string;
  review_status: 'AI_DRAFT' | 'NEEDS_VERIFICATION' | 'PHYSICIAN_CONFIRMED';
  clinical_state: {
    chief_complaint?: string;
    symptoms?: string[];
    onset?: string;
    duration?: string;
    severity?: number;
    location?: string;
    character?: string;
    radiation?: string;
    associated_symptoms?: string[];
    timing?: string;
    aggravating_factors?: string[];
    relieving_factors?: string[];
    ayush?: {
      prakriti?: string;
      vikriti?: string;
      agni?: string;
      koshtha?: string;
      ahara_vihara?: string;
      doshas?: [number, number, number];
    };
    red_flags?: {
      rule_id: string;
      title: string;
      reason: string;
      severity: string;
    }[];
    vitals?: Record<string, any>;
    medications?: string[];
    confidence?: number;
  };
  submitted_at: string;
  clinician_notes?: string;
  fhir_bundle_id?: string;
  documents: Array<{
    id: string;
    document_id?: string;
    name: string;
    file_name: string;
    size: string;
    file_size?: number;
    mime_type?: string;
    type: string;
    document_type?: string;
    status?: string;
    failure_code?: string;
    uploaded_at?: string;
    localOnly?: boolean;
    url?: string;
    extractions?: Array<MedicalRecordExtraction>;
    [key: string]: unknown;
  }>;
  medical_records?: Array<MedicalRecordExtraction>;
  timeline: Array<Record<string, unknown>>;
};

export type MedicalRecordExtraction = {
  id: string;
  document_id: string;
  document_name: string;
  document_type: string;
  field_type: string;
  field_name: string;
  value: Record<string, any> | string;
  confidence: number;
  ocr_confidence?: number;
  source_page?: number;
  source_text?: string;
  status?: string;
};

